apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: arashgh/uni-project:95bd3b3
        ports:
        - containerPort: 8080
        env:
        - name: ENV_VAR
          value: "production"
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: { duration: 60s }
      - setWeight: 50
      - pause: { duration: 60s }
      - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30008
  type: NodePort

