apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Arash-81/k8s-manifests' # Replace with your repository
    targetRevision: main # Branch to sync
    path: go-app # Directory where YAML files are stored
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

